//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeAddin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfficeAddin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYN.
        /// </summary>
        internal static string btnByn_Label {
            get {
                return ResourceManager.GetString("btnByn_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUR.
        /// </summary>
        internal static string btnEur_Label {
            get {
                return ResourceManager.GetString("btnEur_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Pane.
        /// </summary>
        internal static string btnTaskPane_Label {
            get {
                return ResourceManager.GetString("btnTaskPane_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        internal static string btnUsd_Label {
            get {
                return ResourceManager.GetString("btnUsd_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string grpCurrency_Label {
            get {
                return ResourceManager.GetString("grpCurrency_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Pane.
        /// </summary>
        internal static string grpTaskPane_Label {
            get {
                return ResourceManager.GetString("grpTaskPane_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot;
        ///          xmlns:default=&quot;OfficeAddin.Connect&quot;
        ///          onLoad=&quot;Ribbon_OnLoad&quot;&gt;
        ///  &lt;ribbon&gt;
        ///    &lt;tabs&gt;
        ///      &lt;tab id=&quot;tabOfficeAddin&quot; getLabel=&quot;Ribbon_GetLabel&quot;&gt;
        ///        &lt;group id=&quot;grpCurrency&quot; getLabel=&quot;Ribbon_GetLabel&quot;&gt;
        ///          &lt;button id=&quot;btnUsd&quot; size=&quot;large&quot; imageMso=&quot;FunctionsMathTrigInsertGallery&quot; getLabel=&quot;Ribbon_GetLabel&quot; onAction=&quot;ButtonUsd_OnClick&quot; /&gt;
        ///          &lt;button id=&quot;btnEu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ribbon {
            get {
                return ResourceManager.GetString("Ribbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Addin.
        /// </summary>
        internal static string tabOfficeAddin_Label {
            get {
                return ResourceManager.GetString("tabOfficeAddin_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addin Task Pane.
        /// </summary>
        internal static string TaskPaneHeader {
            get {
                return ResourceManager.GetString("TaskPaneHeader", resourceCulture);
            }
        }
    }
}
